config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'rec_sites#index'
  get 'campsite/:id', to: 'rec_sites#show'

  get 'campsites', to: 'rec_sites#index'
  get 'campsite/:id/book-now', to: 'bookings#new'
  get 'campsite/:id/book-now/confirmed', to: 'bookings#confirmed'

  get 'my-bookings', to: 'bookings#index'
  get 'my-bookings/:uuid', to: 'bookings#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :rec_site
end

app/models/rec_site.rb
class RecSite < ApplicationRecord
  has_many :bookings
  has_many :users, :through => :bookings
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :rec_sites, :through => :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
        :omniauthable, :omniauth_providers => [:google_oauth2, :facebook]

   def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  def new
    @recsite = RecSite.find(params[:id])
  end

  def confirmed
    @recsite = RecSite.find(params[:id])

    @booking = Booking.new
    @booking.user_id = current_user.id
    @booking.rec_site_id = @recsite.id
    @booking.price = 30
    @booking.guests_adult = 6
    @booking.guests_child = 0
    @booking.uuid = SecureRandom.uuid
    @booking.save
  end

  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find_by uuid: params[:uuid]
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end

    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end

    def failure
      redirect_to root
    end
end

app/controllers/rec_sites_controller.rb
class RecSitesController < ApplicationController
  def index
    @rec_sites = RecSite.all
  end

  def show
    @recsite = RecSite.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/views/bookings/confirmed.html.erb
<div class="confirmed-page">
  <div class="container">
    <div class="info-text">
      <h3>Booking Confirmed!</h3>
      <span>Check-in begins at 2:00pm on Friday, August 5 and you'll be staying for 2 nights.</span>
    </div>

    <hr />

    <div class="campsite-details">
      <h3><%= @recsite.name %></h3>
      <span class="accom-level <%= @recsite.site_class.downcase %>"><%= @recsite.site_class %></span>

      <div class="logistics">
        <span class="address address-1">-35.512031, 141.322908</span>
        <span class="address address-2">Victoria, Australia</span>
        <span class="checkinout-dates">Fri, Aug 5 - Sun, Aug 7</span>
      </div>

      <div class="map">
        <iframe
          frameborder="0" style="border:0"
          src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyDIjVO-RYkBOZkW_DBOy0g4551G4ZCKPQI&origin=melbourne,victoria&destination=<%= @recsite.latitude %>,<%= @recsite.longitude %>" allowfullscreen>
        </iframe>
      </div>

      <div class="big-dates">
        <div class="left-col">
          <span class="bigger">Check-in</span>
          <span>Fri, Aug 5, 2016</span>
          <span>2:00PM</span>
        </div>

        <div class="right-col">
          <span class="bigger">Check-out</span>
          <span>Sun, Aug 7, 2016</span>
          <span>11:00AM</span>
        </div>
      </div>

      <div class="extra-buttons">
        <a href="#"><button class="btn">Add to calendar</button></a>
        <a href="/"><button class="btn">Home Page</button></a>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <h1>My bookings</h1>

  <div class="campsite-listings">
    <% @bookings.each do |b| %>
      <a href="/my-bookings/<%= b.uuid %>">
        <div class="listing" style='background-image: url(<%= image_path("campsites/#{b.rec_site.photo_id_1}") %>);'>
          <div class="listing-text">
            <span class="title"><%= b.rec_site.name %></span>
            <span class="availability">3 Sites Remaining</span>
            <div class="facilities">
              <%= icon('fire', title: "Fire pits") %>
              <%= icon('cutlery', title: "BBQs") %>
              <%= icon('bed', title: "Campsites") %>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="booking-page">
  <div class="campsite-image" style='background-image: url(<%= image_path("campsites/#{@recsite.photo_id_1}") %>'>
    <span class="title"><%= @recsite.name %></span>
  </div>
  <div class="container">

    <div class="booking-content guest-info">
      <div class="left-col">
        <span>Guest</span>
      </div>

      <div class="right-col">
        <span><%= current_user.email %></span>
      </div>
    </div>

    <hr />

    <div class="booking-content checkinout-dates">
      <div class="left-col">
        <span>Check-in</span>
        <span>Check-out</span>
      </div>

      <div class="right-col">
        <span>Fri, Aug 5</span>
        <span>Sun, Aug 7</span>
      </div>
    </div>

    <hr />

    <div class="booking-content site-type">
      <div class="left-col">
        <span>Site type</span>
      </div>

      <div class="right-col">
        <span>Assigned by ranger</span>
      </div>
    </div>

    <hr />

    <div class="booking-content pricing">
      <div class="left-col">
        <span>Unpowered site (2 nights)</span>
        <span>Promo code</span>
      </div>

      <div class="right-col">
        <span>$30</span>
        <span>Not Applied</span>
      </div>
    </div>

    <hr />

    <div class="booking-content payment-method">
      <div class="left-col">
        <span>Payment method</span>
      </div>

      <div class="right-col">
        <span class="active-payment"><i class="fa fa-credit-card-alt"></i>Credit Card</span>

        <div class="payment-method-options">
          <span class="android-pay"><i class="fa fa-android"></i>Android Pay</span>
          <span class="apple-pay"><i class="fa fa-apple"></i>Apple Pay</span>
          <span class="bitcoin"><i class="fa fa-bitcoin"></i>BitCoin</span>
          <span class="credit-card current"><i class="fa fa-credit-card-alt"></i>Credit Card</span>
        </div>
      </div>
    </div>

    <hr />

    <div class="booking-content total">
      <div class="left-col">
        <span>Total</span>
      </div>

      <div class="right-col">
        <span>$30</span>
      </div>
    </div>

    <hr />

    <div class="booking-content need-to-know">
      <h3>Need to know</h3>

      <ul>
        <li>Purchase is non-refundable</li>
        <li>This site is unpowered</li>
        <li>Visitors must bring their own tents and equipment</li>
        <li>No guarantees can be made regarding weather</li>
      </ul>
    </div>

    <div class="booking-content pay-now">
      <a href="/campsite/<%= @recsite.id %>/book-now/confirmed"><button class="btn pay-now"><span class="payment-type-text"><i class="fa fa-credit-card-alt"></i>Credit Card</span></button></a>
    </div>
  </div>
</div>
<div class="modal-background hidden">
  <div class="confirm-purchase-modal">
    <span class="close">x</span>
    <button class="btn btn-success">Confirm Purchase</button>
    <%= image_tag('loading-spinner.gif', class: "loading-gif hidden", loop: "infinite") %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="confirmed-page">
  <div class="container">
    <div class="info-text">
      <h3>Booking Confirmed!</h3>
      <span>Check-in begins at 2:00pm on Friday, August 5 and you'll be staying for 2 nights.</span>
    </div>

    <hr />

    <div class="campsite-details">
      <h3><%= @booking.rec_site.name %></h3>
      <span class="accom-level <%= @booking.rec_site.site_class.downcase %>"><%= @booking.rec_site.site_class %></span>

      <div class="logistics">
        <span class="address address-1">-35.512031, 141.322908</span>
        <span class="address address-2">Victoria, Australia</span>
        <span class="checkinout-dates">Fri, Aug 5 - Sun, Aug 7</span>
      </div>

      <div class="map">
        <iframe
          frameborder="0" style="border:0"
          src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyDIjVO-RYkBOZkW_DBOy0g4551G4ZCKPQI&origin=melbourne,victoria&destination=<%= @booking.rec_site.latitude %>,<%= @booking.rec_site.longitude %>" allowfullscreen>
        </iframe>
      </div>

      <div class="big-dates">
        <div class="left-col">
          <span class="bigger">Check-in</span>
          <span>Fri, Aug 5, 2016</span>
          <span>2:00PM</span>
        </div>

        <div class="right-col">
          <span class="bigger">Check-out</span>
          <span>Sun, Aug 7, 2016</span>
          <span>11:00AM</span>
        </div>
      </div>

      <div class="extra-buttons">
        <a href="#"><button class="btn">Add to calendar</button></a>
        <a href="/"><button class="btn">Home Page</button></a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampsitesTonightRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navbar" %>
    <div class="container full-height">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Campsites Tonight</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-top">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("Available campsites", campsites_path) %></li>
        <li><%= link_to('My bookings', my_bookings_path) %></li>
        <% if current_user %>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/rec_sites/index.html.erb
<div class="container">
  <h1>Available Campsites</h1>

  <div class="campsite-listings">
    <% 10.times do %>
      <!--<a href="/campsite/1">
        <div class="listing" style="background-image: url(<%= image_path('campsites/fire-bin.jpeg') %>);">
          <div class="listing-text">
            <span class="title">Otways National Park</span>
            <span class="availability">3 Sites Remaining</span>
            <div class="facilities">
              <i>BBQ</i>
              <i>Fires</i>
              <i>Fixed Accommodation</i>
            </div>
          </div>
        </div>
      </a>-->
    <% end %>
    <% @rec_sites.shuffle.each do |r| %>
    <a href="/campsite/<%= r.id %>">
      <div class="listing" style='background-image: url(<%= image_path("campsites/#{r.photo_id_1}") %>);'>
        <div class="listing-text">
          <span class="title"><%= r.name %></span>
          <span class="availability"><%= rand(1..15) %> Sites Remaining</span>
          <div class="facilities">
            <%= icon('fire', title: "Fire pits") %>
            <%= icon('cutlery', title: "BBQs") %>
            <%= icon('bed', title: "Campsites") %>
          </div>
        </div>
      </div>
    </a>
    <% end %>
  </div>
</div>

app/views/rec_sites/show.html.erb
<div class="campsite-page">
  <div class="campsite-image" style='background-image: url(<%= image_path("campsites/#{@recsite.photo_id_1}") %>)'></div>
  <div class="container">
    <div class="campsite-info-text">
      <div class="left-col">
        <span class="title"><%= @recsite.name %></span>
        <span class="accom-level basic"><%= @recsite.site_class %></span>
      </div>
      <div class="right-col">
        <%= icon('heart-o', class: 'shortlist') %>
      </div>
      <hr />

      <div class="address-text">
        <span class="address address-1"><%= @recsite.latitude %>, <%= @recsite.longitude %></span>
        <span class="address address-2">Victoria, Australia</span>
      </div>
    </div>

    <div class="map">
      <iframe
        frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyDIjVO-RYkBOZkW_DBOy0g4551G4ZCKPQI&origin=melbourne,victoria&destination=<%= @recsite.latitude %>,<%= @recsite.longitude %>" allowfullscreen>
      </iframe>
    </div>

    <div class="extra-info">
      <div class="weather-container">
        <span class="weather weather-forecast">Forecast: Some Showers <%= icon('cloud') %></span>
        <span class="weather weather-temp"><span class="high"><%= maxtemp = rand(5..20) %>℃</span> | <span class="low"><%= rand(5..maxtemp) %>℃</span></span>
      </div>
      <hr />
      <div class="comment-text">
        <h3>Some Extra Info</h3>
        <p>
          <% unless @recsite.camping_c || @recsite.comments %>
            No information has been added for this destination.
          <% end %>

          <%= @recsite.comments %>
          <%= @recsite.camping_c %>
        </p>
      </div>
    </div>

    <div class="amenities">
      <h3>Amenities</h3>
      <div class="tabs">
        <div class="tab-nav">
          <span class="area active">AREA</span>
          <span class="campsite">CAMPSITE</span>
          <span class="supplies">SUPPLIES</span>
        </div>
        <div class="tab-area tab">
          <ul>
            <li><%= icon('bed') %> 10 Campsites</li>
            <li><%= icon('life-buoy') %> Swimming</li>
            <li><%= icon('blind') %> Hiking trails</li>
            <li><%= icon('bicycle') %> Mountain bike trails</li>
            <li><%= icon('road') %> Sealed roads</li>
          </ul>
        </div>

        <div class="tab-campsite tab hidden">
          <ul>
            <li><%= icon('recycle') %> Recycling</li>
            <li><%= icon('lightbulb-o') %> Lights</li>
            <li><%= icon('tint') %> Drinking taps</li>
            <li><%= icon('male') %> <%= icon('female') %> Toilets</li>
            <li><%= icon('plug') %> Unpowered sites only</li>
          </ul>
        </div>

        <div class="tab-supplies tab hidden">
          <ul>
            <li><%= icon('coffee') %> Cafe</li>
            <li><%= icon('beer') %> Pub</li>
            <li><%= icon('shopping-basket') %> Supermarket</li>
          </ul>
        </div>
      </div>
    </div>

    <div class="need-to-know">
      <h3>Need to know</h3>
      <ul>
        <li><%= icon('users') %> Bookings are for 6 people</li>
        <li><%= icon('bug') %> Snakes are common in summer</li>
        <li><%= icon('user-plus') %> 18+ to book</li>
        <li><%= icon('beer') %> Alcohol friendly</li>
        <li><%= icon('info-circle') %> Rangers available 09:00-17:00 All Days</li>
      </ul>
    </div>
  </div>

  <a href="/campsite/<%= @recsite.id %>/book-now"><button class="book-now btn btn-book-now">Book Now | $30</button></a>
</div>